name: Deploy Function App via Matrix

on:
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy_to_non_prod:
    name: Deploy to ${{ matrix.env }}
    strategy:
      matrix:
        env: [dev, qa]
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ matrix.env }}
      app_name: orderproc
      deployment_name: orderproc-${{ matrix.env }}
      function_app_name: cchat-fn-orderproc-${{ matrix.env }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
