name: Order Processor Func App Create Release for PR
concurrency: Order Processor Func App Create Release for PR

on:
  pull_request:
    branches: [ 'main' ]
    
env:
  project-path: OrderProcessorFuncApp/OrderProcessorFuncApp.csproj
  deploy-templates-path: ./.github/bicep-order-processor-func-app
  applicationName: orderproc
  location: australiasoutheast
        
jobs:
     
  generate_version_number:
    name: Generate Version Number
    runs-on: ubuntu-latest
    steps:
      - name: Build Version Number
        shell: bash
        run: |
          echo "BUILD_VERSION=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
    
    outputs:
      VersionNumber: ${{ env.BUILD_VERSION }}
  
  build_and_publish:
    name: Build and Publish
    needs:
      - generate_version_number
    uses: ./.github/workflows/build-and-publish-artifacts.yml
    with:
        project-path: '${{ env.project-path }}'
        deploy-templates-path: '${{ env.deploy-templates-path }}'
        versionNumber: ${{ needs.generate_version_number.outputs.VersionNumber }}
          
  DEV:
    name: DEV
    needs:
      - generate_version_number
      - build_and_publish
    uses: ./.github/workflows/deploy-function-app.yml
    with:
      applicationName: ${{ env.applicationName }}
      location: ${{ env.location }}
      versionNumber: ${{ needs.generate_version_number.outputs.VersionNumber }}
      environment: dev
    secrets:
      credentials: ${{ secrets.AZURE_CREDENTIALS }}
      subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          
