name: Provision Resources

on:
  workflow_call:
    inputs:
      applicationName:
        type: string
        required: true
        description: Application name
        
      environment:
        type: string
        required: true
        description: Environment name
      
      location:
        type: string
        required: true
        description: Resource group location
      
      versionNumber:
        type: string
        required: true
        description: Version number to track deployments
        
jobs:
  provisioning:
    name: Provisioning
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:      
      - name: Download deployment artifacts
        uses: actions/download-artifact@v4
        with:
          name: deploy
          path: deploy
          
      - name: Download Application Binaries
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.versionNumber }}
          path: ${{ inputs.versionNumber }}
          
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Provision Azure Resources
        uses: azure/arm-deploy@v2
        with:
          failOnStdErr: false
          deploymentName: "${{ env.ARTIFACT_NAME }}${{inputs.environment}}"
          scope: subscription
          region: ${{ inputs.location }}
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          template: deploy/main.bicep
          parameters: >
            appName=${{ inputs.applicationName }}
            version=${{ inputs.versionNumber }}
            environment=${{ inputs.environment }}
            location=${{ inputs.location }}
            
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        with:
          app-name: 'cchat-fn-${{ inputs.applicationName }}-${{ inputs.environment }}'
          slot-name: 'Production'
          package: '${{ needs.generate_version_number.outputs.VersionNumber }}'

      - name: Logout from Azure
        uses: azure/cli@v2
        with:
          inlineScript:
            az logout            
            
