name: testcicd
concurrency: testcicd

on:
  pull_request:
    branches: [ 'main' ]
    
env:
 project-path: OrderProcessorFuncApp/OrderProcessorFuncApp.csproj
 deploy-templates-path: ./.github/bicep-order-processor-func-app
  

jobs:  
  generate_version_number:
    name: Generate Version Number
    runs-on: ubuntu-latest
    steps:
      - name: Build Version Number
        shell: bash
        run: |
          echo "BUILD_VERSION=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
    
    outputs:
      VersionNumber: ${{ env.BUILD_VERSION }}
  
  build:
    name: Build
    needs:
      - generate_version_number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x     

      - name: Create Artifact
        shell: bash
        run: dotnet publish ${{ env.project-path }} -c Release -o ${{ needs.generate_version_number.outputs.VersionNumber }}

      - name: Publish Artifact - App
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.generate_version_number.outputs.VersionNumber }}
          path: ${{ needs.generate_version_number.outputs.VersionNumber }}/**
          if-no-files-found: error

      - name: Publish Artifact - Templates
        uses: actions/upload-artifact@v4
        with:
          name: deploy
          path: ${{ env.deploy-templates-path }}
          if-no-files-found: error
  
  DEV:
    name: DEV
    runs-on: ubuntu-latest
    environment: 
      name: dev
    needs:
      - generate_version_number
      - build
    steps:      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}
          
      - name: Logout from Azure
        uses: azure/cli@v2
        with:
          inlineScript:
            az logout   

        
          
